name: Backup automático de index.html

on:
  push:
    branches:
      - main

jobs:
  backup:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v3

      - name: Crear carpeta de backups
        run: mkdir -p backups

      - name: Copiar index.html con fecha
        run: cp index.html backups/index_$(date +'%Y-%m-%d_%H-%M-%S').html

      - name: Configurar Git y subir a rama backups
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          git config --global user.name "Gustavo Gramajo (GitHub Actions)"
          git config --global user.email "consultoresgrtuc@gmail.com"
          git checkout -B backups
          git add backups/
          git commit -m "Backup automático de index.html [$(date)]" || echo "Sin cambios para confirmar"
          git push https://x-access-token:${GH_TOKEN}@github.com/consultoresgrtuc-arg/portal-consultora.git backups --force
